# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='root', max_length=5),
            preserve_default=False,
        ),
    ]
