# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_usergroup_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='up_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
