# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_usergroup_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, 'superuser'), (2, 'general_user'), (3, 'temp_user')], default=1),
        ),
    ]
