# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buseiness',
            name='english_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
