# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_buseiness_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Application')),
                ('h_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host')),
            ],
        ),
    ]
