# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='a_obj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='h_obj',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
