# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20171125_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='monitor.Host'),
        ),
    ]
